=== DmitryNeverovich/DmitryNeverovich/task4/task04/xml-resources/jaxb/Jaxbgreenhouse/Greenhouse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
            targetNamespace="http://www.example.com/Greenhouse"
            xmlns:tn="http://www.example.com/Greenhouse">
	
    <element name="greenhouse">
        <complexType>
            <sequence>
                <element name="flower" type="tn:Flower" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
        
    <complexType name="Flower">
        <sequence>
            <element name="name" type="string"/>
            <element name="hight" type="tn:Hight"/>
            <element name="soil" type="tn:Soil"/>
            <element name="origin" type="string"/>
            <element name="multiplying" type="tn:Multiplying"/>
            <element name="visualParameters" type="tn:VisualParameters"/>
        </sequence>
        <attribute name="id" type="tn:Number" use="required"/>
        <attribute name="family" type="string" use="required"/>
    </complexType>
    
    <simpleType name="Hight">
        <restriction base="integer">
            <minInclusive value="5"/>
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>  
    
     <simpleType name="Number">
        <restriction base="ID">
            <pattern value="[a-z][0-9]+"/>
        </restriction>
    </simpleType>           
                                        
    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="podzolic"/>
            <enumeration value="sod-podzolic"/>
            <enumeration value="dirt"/>
        </restriction>
    </simpleType>
		
    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="plate"/>
            <enumeration value="seed"/>
            <enumeration value="cutting"/>
        </restriction>
    </simpleType>
	
    <complexType name="VisualParameters">
        <sequence>
            <element name="colorStalk" type="string"/>
            <element name="colorList" type="string"/>
            <element name="growingtips" type="tn:Growingtips"/>				
        </sequence>
    </complexType>
		
    <complexType name="Growingtips">
        <sequence>
            <element name="term" type="integer"/>
            <element name="light" type="string"/>
            <element name="water" type="integer"/>
        </sequence>
    </complexType>		
  
</schema>

=== DmitryNeverovich/DmitryNeverovich/task4/task04/xml-source/Greenhouse.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?> 
<gh:greenhouse xmlns:gh="http://www.example.com/Greenhouse" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.example.com/Greenhouse Greenhouse.xsd">
    <flower id="n1" family="Orchids">
        <name>Orchid</name>
        <hight>20</hight>
        <soil>podzolic</soil>
        <origin>Europe</origin>
        <multiplying>plate</multiplying>
        <visualParameters>
            <colorStalk>green</colorStalk>
            <colorList>green</colorList> 
            <growingtips>
                <temperature>20</temperature>
                <light>average</light>
                <water>3</water>
            </growingtips>
        </visualParameters>
    </flower>
    <flower id="n2" family="Liliaceae">
        <name>Lilium</name>
        <hight>10</hight>
        <soil>dirt</soil>
        <origin>Asia</origin>
        <multiplying>seed</multiplying>
        <visualParameters>
            <colorStalk>green</colorStalk>
            <colorList>green</colorList> 
            <growingtips>
                <temperature>20</temperature>
                <light>average</light>
                <water>2</water>
            </growingtips>
        </visualParameters>
    </flower>
    <flower id="n3" family="Paeoniaceae">
        <name>Peony</name>
        <hight>12</hight>
        <soil>podzolic</soil>
        <origin>Europe</origin>
        <multiplying>seed</multiplying>
        <visualParameters>
            <colorStalk>green</colorStalk>
            <colorList>green</colorList> 
            <growingtips>
                <temperature>23</temperature>
                <light>average</light>
                <water>2</water>
            </growingtips>
        </visualParameters>
    </flower>
	<flower id="n4" family="Liliaceae">
        <name>Tulip</name>
        <hight>20</hight>
        <soil>dirt</soil>
        <origin>Europe</origin>
        <multiplying>seed</multiplying>
        <visualParameters>
            <colorStalk>green</colorStalk>
            <colorList>green</colorList> 
            <growingtips>
                <temperature>24</temperature>
                <light>high</light>
                <water>4</water>
            </growingtips>
        </visualParameters>
    </flower>
</gh:greenhouse>
